"""empty message

Revision ID: 211875963f3e
Revises: fa91a13a1c1a
Create Date: 2022-08-13 12:12:18.576314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211875963f3e'
down_revision = 'fa91a13a1c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('numero', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'numero')
    # ### end Alembic commands ###
