"""empty message

Revision ID: 979a704c979c
Revises: 211875963f3e
Create Date: 2022-08-13 13:41:05.671543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979a704c979c'
down_revision = '211875963f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'dia',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'dia',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
