"""0.0

Revision ID: fa91a13a1c1a
Revises: 
Create Date: 2022-08-03 22:26:55.103449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa91a13a1c1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'dia',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('schedule', 'hora',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('schedule', 'tipo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('stats', 'time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'plan',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'hash',
               existing_type=mysql.VARCHAR(length=999),
               nullable=False)
    op.alter_column('users', 'fecha',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'fecha',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'hash',
               existing_type=mysql.VARCHAR(length=999),
               nullable=True)
    op.alter_column('users', 'plan',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('stats', 'time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('schedule', 'tipo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('schedule', 'hora',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('schedule', 'dia',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
